controllers:
    resource: ../../src/Controller
    prefix: /api
    name_prefix: api.
    trailing_slash_on_root: true
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
    #type: attributes
