controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login:
  path: /api/user/login

gesdinet_jwt_refresh_token:
  path: /api/user/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
